### ISSUE TITLE
Error:  ValueError: too many values to unpack

### ISSUE THREAD

**Issue by longerking** [JuneYaooo/llm_structure_tool#1]
创建环境后，运行实例失败，出现如下错误
似乎没有去下载模型
```
(llm_structure) wonderswsl@WondersWL:/mnt/g/GitHub/LLM/llm_structure_tool$ python app.py
/home/wonderswsl/miniconda3/envs/llm_structure/lib/python3.9/site-packages/gradio/outputs.py:22: UserWarning: Usage of gradio.outputs is deprecated, and will not be supported in the future, please import your components from gradio.components
  warnings.warn(
Running on local URL:  http://0.0.0.0:33366
222 pulse start query
lora_name, last_lora_name 不使用
Traceback (most recent call last):
  File "/home/wonderswsl/miniconda3/envs/llm_structure/lib/python3.9/site-packages/gradio/routes.py", line 437, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/wonderswsl/miniconda3/envs/llm_structure/lib/python3.9/site-packages/gradio/blocks.py", line 1352, in process_api
    result = await self.call_function(
  File "/home/wonderswsl/miniconda3/envs/llm_structure/lib/python3.9/site-packages/gradio/blocks.py", line 1077, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/wonderswsl/miniconda3/envs/llm_structure/lib/python3.9/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/wonderswsl/miniconda3/envs/llm_structure/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/wonderswsl/miniconda3/envs/llm_structure/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/mnt/g/GitHub/LLM/llm_structure_tool/app.py", line 67, in on_query
    res = pulse_query(model_name, select_lora, field_type, field_name, value_range, query)
  File "/mnt/g/GitHub/LLM/llm_structure_tool/finetune/pulse_utils.py", line 329, in pulse_query
    model, tokenizer = load_model(model_name,lora_name)
ValueError: too many values to unpack (expected 2)
```

**Comment by longerking** [comment]
> 创建环境后，运行实例失败，出现如下错误 似乎没有去下载模型
> 
> ```
> (llm_structure) wonderswsl@WondersWL:/mnt/g/GitHub/LLM/llm_structure_tool$ python app.py
> /home/wonderswsl/miniconda3/envs/llm_structure/lib/python3.9/site-packages/gradio/outputs.py:22: UserWarning: Usage of gradio.outputs is deprecated, and will not be supported in the future, please import your components from gradio.components
>   warnings.warn(
> Running on local URL:  http://0.0.0.0:33366
> 222 pulse start query
> lora_name, last_lora_name 不使用
> Traceback (most recent call last):
>   File "/home/wonderswsl/miniconda3/envs/llm_structure/lib/python3.9/site-packages/gradio/routes.py", line 437, in run_predict
>     output = await app.get_blocks().process_api(
>   File "/home/wonderswsl/miniconda3/envs/llm_structure/lib/python3.9/site-packages/gradio/blocks.py", line 1352, in process_api
>     result = await self.call_function(
>   File "/home/wonderswsl/miniconda3/envs/llm_structure/lib/python3.9/site-packages/gradio/blocks.py", line 1077, in call_function
>     prediction = await anyio.to_thread.run_sync(
>   File "/home/wonderswsl/miniconda3/envs/llm_structure/lib/python3.9/site-packages/anyio/to_thread.py", line 33, in run_sync
>     return await get_asynclib().run_sync_in_worker_thread(
>   File "/home/wonderswsl/miniconda3/envs/llm_structure/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
>     return await future
>   File "/home/wonderswsl/miniconda3/envs/llm_structure/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 807, in run
>     result = context.run(func, *args)
>   File "/mnt/g/GitHub/LLM/llm_structure_tool/app.py", line 67, in on_query
>     res = pulse_query(model_name, select_lora, field_type, field_name, value_range, query)
>   File "/mnt/g/GitHub/LLM/llm_structure_tool/finetune/pulse_utils.py", line 329, in pulse_query
>     model, tokenizer = load_model(model_name,lora_name)
> ValueError: too many values to unpack (expected 2)
> ```

似乎再WSL2  1060 + 6G中不工作，换到Ubuntu20+P40 24G正常下载模型了。

依赖于模型：https://github.com/openmedlab/PULSE/tree/main


硬件条件：https://github.com/openmedlab/PULSE/blob/main/README.md#:~:text=%E4%B8%8B%E8%A1%A8%E6%8F%90%E4%BE%9B%E4%BA%86%E4%B8%80%E4%B8%AAbatch%20size%3D1%E6%97%B6%E6%9C%AC%E5%9C%B0%E9%83%A8%E7%BD%B2PULSE%E8%BF%9B%E8%A1%8C%E6%8E%A8%E7%90%86%E6%89%80%E9%9C%80%E7%9A%84%E6%98%BE%E5%AD%98%E5%A4%A7%E5%B0%8F%E3%80%82

![image](https://github.com/JuneYaooo/llm_structure_tool/assets/37200736/fa91186d-ba99-46af-9141-d2891f291238)

**Comment by longerking** [comment]
> > 创建环境后，运行实例失败，出现如下错误 似乎没有去下载模型
> > ```
> > (llm_structure) wonderswsl@WondersWL:/mnt/g/GitHub/LLM/llm_structure_tool$ python app.py
> > /home/wonderswsl/miniconda3/envs/llm_structure/lib/python3.9/site-packages/gradio/outputs.py:22: UserWarning: Usage of gradio.outputs is deprecated, and will not be supported in the future, please import your components from gradio.components
> >   warnings.warn(
> > Running on local URL:  http://0.0.0.0:33366
> > 222 pulse start query
> > lora_name, last_lora_name 不使用
> > Traceback (most recent call last):
> >   File "/home/wonderswsl/miniconda3/envs/llm_structure/lib/python3.9/site-packages/gradio/routes.py", line 437, in run_predict
> >     output = await app.get_blocks().process_api(
> >   File "/home/wonderswsl/miniconda3/envs/llm_structure/lib/python3.9/site-packages/gradio/blocks.py", line 1352, in process_api
> >     result = await self.call_function(
> >   File "/home/wonderswsl/miniconda3/envs/llm_structure/lib/python3.9/site-packages/gradio/blocks.py", line 1077, in call_function
> >     prediction = await anyio.to_thread.run_sync(
> >   File "/home/wonderswsl/miniconda3/envs/llm_structure/lib/python3.9/site-packages/anyio/to_thread.py", line 33, in run_sync
> >     return await get_asynclib().run_sync_in_worker_thread(
> >   File "/home/wonderswsl/miniconda3/envs/llm_structure/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
> >     return await future
> >   File "/home/wonderswsl/miniconda3/envs/llm_structure/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 807, in run
> >     result = context.run(func, *args)
> >   File "/mnt/g/GitHub/LLM/llm_structure_tool/app.py", line 67, in on_query
> >     res = pulse_query(model_name, select_lora, field_type, field_name, value_range, query)
> >   File "/mnt/g/GitHub/LLM/llm_structure_tool/finetune/pulse_utils.py", line 329, in pulse_query
> >     model, tokenizer = load_model(model_name,lora_name)
> > ValueError: too many values to unpack (expected 2)
> > ```
> 
> 似乎再WSL2 1060 + 6G中不工作，换到Ubuntu20+P40 24G正常下载模型了。
> 
> 依赖于模型：https://github.com/openmedlab/PULSE/tree/main
> 
> 硬件条件：https://github.com/openmedlab/PULSE/blob/main/README.md#:~:text=%E4%B8%8B%E8%A1%A8%E6%8F%90%E4%BE%9B%E4%BA%86%E4%B8%80%E4%B8%AAbatch%20size%3D1%E6%97%B6%E6%9C%AC%E5%9C%B0%E9%83%A8%E7%BD%B2PULSE%E8%BF%9B%E8%A1%8C%E6%8E%A8%E7%90%86%E6%89%80%E9%9C%80%E7%9A%84%E6%98%BE%E5%AD%98%E5%A4%A7%E5%B0%8F%E3%80%82
> 
> ![image](https://user-images.githubusercontent.com/37200736/253190553-fa91186d-ba99-46af-9141-d2891f291238.png)

模型可能会下载错误，默认下载到
`~/.cache/huggingface/hub/models--OpenMEDLab--PULSE-7bv5/` 
如果下载错误，则删除已经下的缓存模型重新下载！
